# Generated by Django 4.2.5 on 2023-10-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Authors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField()),
                ("born_date", models.DateField()),
                ("born_location", models.CharField()),
                ("description", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="Quotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tags", models.CharField()),
                ("quotes", models.CharField()),
                ("author", models.ManyToManyField(blank=True, to="newapp.authors")),
            ],
        ),
    ]
