# Generated by Django 4.2.6 on 2023-10-07 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("newapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="authors",
            name="born_date",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="authors",
            name="description",
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name="quotes",
            name="author",
        ),
        migrations.RemoveField(
            model_name="quotes",
            name="tags",
        ),
        migrations.AddField(
            model_name="quotes",
            name="author",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="newapp.authors",
            ),
        ),
        migrations.AddField(
            model_name="quotes",
            name="tags",
            field=models.ManyToManyField(to="newapp.tag"),
        ),
    ]
