
DROP TABLE IF EXISTS students;
CREATE TABLE students (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS groups;
CREATE TABLE groups (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS teachers;
CREATE TABLE teachers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS subjects;
CREATE TABLE subjects (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255)  NOT NULL,
    subjects_teachers NOT NULL,
    FOREIGN KEY (subjects_teachers) REFERENCES  teachers (name)
       ON DELETE CASCADE
);

DROP TABLE IF EXISTS grade;
CREATE TABLE grade (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    student INT,
    subjectname INT,
    grades_by_subject INTEGER,
    wen_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL,

    FOREIGN KEY (student) REFERENCES  students (id)
    FOREIGN KEY (subjectname) REFERENCES  subjects (id)
      ON DELETE SET NULL

);